# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f368d870177288578a7c2930ff405247380bbbc6d946d7365b1d89bcacce2b5a3db8402661ff7f5e4570e870134f078f92c8329bd506837191f2a10ea76a2669

test:
  secret_key_base: 831528a747be1cd0bd3387d93f51548e237ab8aac80812cd78944ad85bd9f57e421bd7896e4314186caa591049c799a4d88aaeb49b0f4eab4a1aeb06d628fbf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
